### ISSUE TITLE
Websocket example does not work - "Connection error"

### ISSUE THREAD

**Issue by CoverJ** [PaxxPatriot/skinport.py#56]
Hey mate,

to recreate I've extended your websocket example with a listener for the `connect_error` event which will continue to print `"Connection error"` on retries.

```
import skinport

client = skinport.Client()


@client.listen("saleFeed")
async def on_sale_feed(data):
    print(data)


@client.listen("maintenanceUpdated")
async def on_maintenance_updated(data):
    print(data)


@client.listen("steamStatusUpdated")
async def on_steam_status_updated(data):
    print(data)

@client.listen("connect_error")
async def on_connect_error(data):
    print(data)


client.run()
```

Output:
```
Connection error
Connection error
Connection error
```

I was trying to get something working by myself and seen your library. I'm happy to do any legwork if you have any ideas and I'll make a PR back if I can get it working

**Comment by PaxxPatriot** [comment]
Thanks for opening this issue. This was known to me and I am also currently trying to debug. I am also in contact with someone from Skinport to find the issue but I have no update yet.
